### ISSUE TITLE
Github action of lint, test and push failed

### ISSUE THREAD

**Issue by bvalot** [galaxyproject/galaxy-tool-repository-template#13]
Hello,

I have 2 problems with the github action on my channel (https://github.com/bvalot/galaxy):
- R lint script failed with the error:
`Error: Unable to resolve action r-lib/actions@master, unable to find version master`

- Some of my wrappers tests failed with the following error:
`2022-12-07T10:19:13.1251849Z galaxy.tool_util.output_checker INFO 2022-12-07 10:19:12,853 [pN:main,p:2376,tN:LocalRunner.work_thread-0] Job error detected, failing job. Reasons are [{'type': 'exit_code', 'desc': 'Fatal error: Exit code 1 ()', 'exit_code': 1, 'code_desc': '', 'error_level': 3}]`

This problems doesn't arrive with planemo run locally. Can I have more information of the cause of this error?

**Comment by bernt-matthias** [comment]
The R problem has recently been solved. See here https://github.com/galaxyproject/tools-iuc/blob/01e8e726d711c0685f46d3146e4fe0f2a1306036/.github/workflows/pr.yaml#L172 You can just change the line.

But seeing all the deprecation warnings on your actions runs I would suggest to  sync your workflows to the IUC ones. I prepared this for you https://github.com/bvalot/galaxy/pull/1 

For the 2nd question: Did you check the html output .. Can you share the link to an actions run?

**Comment by bvalot** [comment]
Thx, I found the correction for the R action.

**Comment by bvalot** [comment]
Galaxy Tool Linting and Tests for push and PR is currently running! I give you more feedback at the end.
Can you just give me how to check the html output?

**Comment by bernt-matthias** [comment]
Go to the run page, e.g. https://github.com/bvalot/galaxy/actions/runs/2508944770 then on the top left there is a "summary". In the list below the workflow overview you find the list of artifacts. You find the planemo test html output in _All tool test results_

From https://github.com/bvalot/galaxy/actions I guess that you push directly to the main branch. With the actions you should not do this. Always use a PR.

**Comment by bvalot** [comment]
> From https://github.com/bvalot/galaxy/actions I guess that you push directly to the main branch. With the actions you should not do this. Always use a PR.

I don't understand?

**Comment by bernt-matthias** [comment]
You should develop new features / changes in branches and integrate them to the main branch using a pull request (once all tests were successful). 

Otherwise the workflow will not run correctly (because the set of changed tools that need to be tested is computed only for the last commit) .. even worse each commit would trigger a deployment to the toolshed and testtoolshed (once you setup the API keys).

**Comment by bvalot** [comment]
The new script seems not to start all the actions? 
Only Setup cache and determine changed repositories is run
That is link to the PR that you mention?

**Comment by bvalot** [comment]
I create a new branch, change version number of the galaxy tools.
The workflow is currently running.
https://github.com/bvalot/galaxy/actions/runs/3639687937

**Comment by bernt-matthias** [comment]
> The workflow is currently running.

Looks good. 20 tool tests successful and no failure/error.

**Comment by bvalot** [comment]
Great. The problems must be link to the old workflow
Thanks.
